services:
  web:
    build: .
    container_name: customer-order-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: customer-order-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: donfiles.online

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1   
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: donfiles.online
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:


